apiVersion: v1
kind: ConfigMap
metadata:
  name: test-args
data:
  MAX_SLEEP: "3"
  FOLDER: documents
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-script
data:
  test.sh: |
    my_sleep() {
        delay=$(($RANDOM % $1)).$(($RANDOM % 9 ))
        echo "sleeping $delay seconds"
        sleep $delay
    }
    while true
        do
        len=$(($RANDOM % 10000 + 1000))
        file="/${FOLDER}/${POD_NAME}-${len}.txt"
        echo "$POD_NAME writing $file"
        printf '=%.0s' $(seq 1 $len) > $file
        ls -la $FOLDER
        my_sleep $MAX_SLEEP
        echo "$POD_NAME deleting $file"
        rm $file
        my_sleep $MAX_SLEEP
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-file
  labels:
    app: azure-file
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-file
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-file
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: azure-file
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: azure-file
              role: frontend
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: azure-file
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              /scripts/test.sh
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MAX_SLEEP
              valueFrom:
                configMapKeyRef:
                  name: test-args
                  key: MAX_SLEEP
            - name: FOLDER
              valueFrom:
                configMapKeyRef:
                  name: test-args
                  key: FOLDER
          volumeMounts:
            - name: azure-file-share
              mountPath: /documents
              readOnly: false
            - mountPath: /scripts
              name: test-script
              readOnly: true
      volumes:
        - name: azure-file-share
          persistentVolumeClaim:
            claimName: azure-file-pvc
        - name: test-script
          configMap:
            name: test-script
            defaultMode: 0777
